version: 2

models:
  - name: customers
    description: "Dimension table for customers."
    columns:
      - name: dbt_scd_id
        description: "Surrogate key for SCD Type 2."
        tests:
          - unique
          - not_null
  - name: sellers
    description: "Dimension table for sellers."
    columns:
      - name: dbt_scd_id
        description: "Surrogate key for SCD Type 2."
        tests:
          - unique
          - not_null
  - name: products
    description: "Dimension table for products."
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
